site_name: '[use.pat.xyz]'
docs_dir: docs/
nav:
    - Commands: index.md
theme:
  name: 'material'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
repo_url: 'https://github.com/patrikgrill/use-pat-xyz'
site_url: https://use.pat.xyz
plugins:
  - search
